import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import Header from '@/components/ui/Header/Header'
import Footer from '@/components/ui/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.style} mx-32`}>
      <Header/>   
        {children}
        <Footer/>
      </body>
    </html>
  )
}
